import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    const allProducts = <Product> [
      Product(
        category: Category.FRUIT,
        id: 0,
        isFeatured: true,
        name: 'Misket Limon',
        price: 120,
      ),
      Product(
        category: Category.FRUIT,
        id: 1,
        isFeatured: true,
        name: 'Çilek',
        price: 58,
      ),
      Product(
        category: Category.FRUIT,
        id: 2,
        isFeatured: false,
        name: 'Armut',
        price: 35,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 3,
        isFeatured: true,
        name: 'Kırmızı Biber',
        price: 98,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 4,
        isFeatured: false,
        name: 'Domates',
        price: 34,
      ),
      Product(
        category: Category.FRUIT,
        id: 5,
        isFeatured: false,
        name: 'Karpuz',
        price: 12,
      ),
      Product(
        category: Category.FRUIT,
        id: 6,
        isFeatured: false,
        name: 'Limon',
        price: 16,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 7,
        isFeatured: true,
        name: 'Karnabahar',
        price: 40,
      ),
      Product(
        category: Category.FRUIT,
        id: 8,
        isFeatured: true,
        name: 'Ekşi Elma',
        price: 198,
      ),
      Product(
        category: Category.FRUIT,
        id: 9,
        isFeatured: true,
        name: 'Kayısı',
        price: 58,
      ),
      Product(
        category: Category.FRUIT,
        id: 10,
        isFeatured: false,
        name: 'Kiraz',
        price: 18,
      ),
      Product(
        category: Category.FRUIT,
        id: 11,
        isFeatured: false,
        name: 'Portakal',
        price: 28,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 12,
        isFeatured: false,
        name: 'Sarımsak',
        price: 34,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 13,
        isFeatured: true,
        name: 'Misket Limon',
        price: 18,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 14,
        isFeatured: true,
        name: 'Salatalık',
        price: 27,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 15,
        isFeatured: true,
        name: 'Patates',
        price: 16,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 16,
        isFeatured: true,
        name: 'Dolma Biber',
        price: 16,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 17,
        isFeatured: false,
        name: 'Prokoli',
        price: 175,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 18,
        isFeatured: true,
        name: 'Ispanak',
        price: 129,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 19,
        isFeatured: false,
        name: 'Mantar',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 20,
        isFeatured: false,
        name: 'Armut',
        price: 45,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 21,
        isFeatured: false,
        name: 'Patlıcan',
        price: 38,
      ),
      Product(
        category: Category.FRUIT,
        id: 22,
        isFeatured: false,
        name: 'Portakal',
        price: 70,
      ),
      Product(
        category: Category.FRUIT,
        id: 23,
        isFeatured: false,
        name: 'Elma',
        price: 70,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 24,
        isFeatured: true,
        name: 'Soğan',
        price: 60,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 25,
        isFeatured: false,
        name: 'Şeker Pancarı',
        price: 178,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 26,
        isFeatured: false,
        name: 'Dolma Biber',
        price: 74,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 27,
        isFeatured: true,
        name: 'Turp',
        price: 38,
      ),
      Product(
        category: Category.FRUIT,
        id: 28,
        isFeatured: true,
        name: 'Üzüm',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 29,
        isFeatured: true,
        name: 'Çilek',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 30,
        isFeatured: true,
        name: 'Kivi',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 31,
        isFeatured: true,
        name: 'Muz',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 32,
        isFeatured: true,
        name: 'Elma',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 33,
        isFeatured: true,
        name: 'Üzüm',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 34,
        isFeatured: true,
        name: 'Kayısı',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 35,
        isFeatured: true,
        name: 'Vişne',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 36,
        isFeatured: true,
        name: 'Erik',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 37,
        isFeatured: true,
        name: 'Karpuz',
        price: 48,
      ),
      Product(
        category: Category.FRUIT,
        id: 38,
        isFeatured: true,
        name: 'Portakal',
        price: 48,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 39,
        isFeatured: true,
        name: 'Havuç',
        price: 48,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 40,
        isFeatured: true,
        name: 'Dolma Biber',
        price: 48,
      ),
      Product(
        category: Category.VEGETABLE,
        id: 41,
        isFeatured: true,
        name: 'Bal Kabağı',
        price: 48,
      ),
    ];
    if (category == Category.ALL) {
      return allProducts;
    } else {
      return allProducts.where((Product p) {
        return p.category == category;
      }).toList();
    }
  }
}
